name: .NET Core

on:
  push:
    paths:
      - 'csharp/dotnet-core/**'
      - '.github/workflows/dotnet-core**'
  pull_request:
    paths:
      - 'csharp/dotnet-core/**'
      - '.github/workflows/dotnet-core**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      working-directory: csharp/dotnet-core
      run: dotnet restore dotnet-core.sln
      
    - name: Build
      working-directory: csharp/dotnet-core
      run: dotnet build --configuration Release --no-restore dotnet-core.sln
      
    - name: Test
      working-directory: csharp/dotnet-core
      run: dotnet test --no-restore --verbosity normal
